---
title: "The modern science"
subtitle: "and its radical origins"
author: "Austin Hart"
institute: "American University"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, rladies, rladies-fonts]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  message=FALSE, warning=FALSE, eval = TRUE, echo = TRUE, 
  fig.align = 'center', dev='svglite', dpi = 300
)
```

class: inverse, middle

<style type="text/css">
.remark-slide-content {
    font-size: 25px;
    padding: 1em 4em 1em 4em;
}
</style>


# The business end
### Life cycle of a causal claim


---

# Scientific inquiry

- Question
- Observation
- Testing
- Inference


---

# Scientific questions

- Investigate "effects of causes"
- Ingredients of a sci question
  - Exposure variable: cause, $X$
  - Outcome variable: effect, $Y$

&nbsp;

> What is the effect of exposure to misinformation (X)
on satisfaction with democracy (Y)?


---

# Theory as guideline and baseline

- Theory: what we *think* we know about $X \rightarrow Y$
  - School of thought A suggests...
  - Alternatively, School B suggests...

- Hypotheses: observable implications of theory
  - In my study, School A predicts...
  - School B predicts...

&nbsp;

> Theories are general stories about the way things work. 
> Hypotheses are specific predictions, derived from theory, about what we will find in the data.


---

# Observation

- Design a study
  - Experiment (randomized controlled trial)
  - Observational (epidemiological)
  - Maybe both!
  
- Collect your data


---

# Testing and inference

- Test the data against convention/status quo hypotheses

- Inferential leaps
  - Is there a relationship? (statistical)
  - Is it causal? (causal)
  - Does it capture what you intended? (measurement)
  - Is the effect general? (external validity)


---
class: inverse, middle

# Nature and radical origins


---

# Modern scientific project

>*New Organon* (1620)
> by Sir Francis Bacon
> 
> Inductive reasoning as the foundation for a new scientific order


---

# What makes it radical?

- Understanding through observation
- Safeguard against confirmation bias

- Challenge status quo without
  - revelation or divination
  - appeal to traditional authority
  
  
---

# Behold, the revolution!

- Question
- Observation
- Testing
- Inference

